# Generated by Django 3.1.1 on 2020-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_stream_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='added_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='airs_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='ends_on',
            field=models.DateTimeField(null=True),
        ),
    ]
