name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pipenv==2020.8.13
    - name: Lint with flake8
      run: |
        # Stop the build for any linting errors.
        flake8 . --count --max-line-length=127 --show-source
    - name: Run django tests
      run: |
        cd sellotape && pipenv sync
        # Create required models
        pipenv run python3 sellotape_dj/manage.py migrate
        # Run the tests
        pipenv run python3 sellotape_dj/manage.py test main_app