name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Install machine dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pipenv==2020.8.13
    - name: Lint with flake8
      run: |
        # Stop the build for any lint errors.
        flake8 . --count --max-line-length=127 --show-source
    - name: Install project dependencies
      run: |
        cd sellotape && pipenv sync
    - name: Run django migrations
      run: |
        cd sellotape
        pipenv run python3 sellotape_dj/manage.py migrate
    - name: Run django tests
      run: |
        cd sellotape
        pipenv run python3 sellotape_dj/manage.py test main_app
